export const voices=['Soprano I','Soprano II','Alto','Tenor','Bass'];
export const formalGroups=[
 {start:1,end:37,endQ:144,number:'I',label:'Exposition and modulating entries',range:'1–37',continuation:'Exposition to 17; D♭ cadence at 25; A♭ cadence at 37'},
 {start:37,startQ:144,end:75,number:'II',label:'Reduced texture and final stretti',range:'37–75',continuation:'Three-part episode; paired entries; five-part stretto from 67'},
];
export const themes=[
 {id:'subject',title:'Subject / tonal answer',location:'Soprano I, bars 1–4; tonal answer: soprano II, bar 3',text:'A falling fourth is followed, across a crotchet rest, by a rising minor ninth. The tonal answer changes the initial fourth to a fifth. The full opening statement continues to the first crotchet of bar 4; later entries often stop after the descending crotchets or alter their continuation. There is no regular countersubject.'},
 {id:'motif',title:'Descending crotchet figure',location:'Soprano I, bars 2–3',text:'The four descending crotchets, G♭–F–E♭–D♭, form the subject’s most persistent accompanying material. Outside the subject they are marked d; their ascending inversion is di. The episodes develop these figures without establishing a separate countersubject.'},
 {id:'sequence',title:'Sequential quaver figure',location:'Soprano I, bars 4–6',text:'Two quavers lead into a longer note, often tied across the bar-line. This figure, q, contributes to the extended opening codetta and returns in the three-part episode at 42–45. The sequence crosses the alla-breve metre in units of three minims.'},
];
export const sections=[
 {start:1,end:10,label:'Opening pair and codetta',entries:'Soprano I 1 → soprano II 3 · codetta 6–10',detail:'The tonal answer overlaps the first subject’s continuation. The descending crotchet figure (d), its ascending inversion (di) and the sequential quaver figure (q) extend the two-part texture. The alto waits until bar 10.'},
 {start:10,end:17,label:'Completion of the exposition',entries:'Alto 10 → tenor 12 · bass 15',detail:'The lower voices complete the descending order of entry. The alto and tenor overlap; a short link precedes the bass. The tenor and bass alter the end of the descending figure to A natural and D natural respectively.'},
 {start:17,end:25,label:'First extended episode',entries:'Crotchet figures in all five parts',detail:'The stepwise material passes between the voices, direct and inverted. The cadence at 25 establishes D♭ major; the lower voices then withdraw as the next subject begins in soprano I.'},
 {start:25,end:37,label:'Modulating entry group',entries:'Soprano I 25 · soprano II 27 · tenor 29 · bass 32',detail:'The soprano’s D♭ entry alters the ninth-leap destination to C♭. The next entry begins on B♭; tenor and bass follow on B♭ and E♭, with major thirds at their closes. The two upper inner parts cross in bars 29–37. An A♭ major cadence closes the first half.'},
 {start:37,end:46,label:'Entry and three-part episode',entries:'Answer form: soprano II 37 · episode 39–46',detail:'The entry on A♭ begins with the cadence. In the retained score allocation, soprano II, tenor and bass carry the ensuing three-part texture. The quaver figure returns at 42–45, recalling the opening codetta.'},
 {start:46,end:55,label:'Answers and paired stretti',entries:'Alto 46:1½ · bass 48 · soprano I 50 → soprano II 50:2 · bass 52 → tenor 53',detail:'The displaced entry at 46 shortens its second note. The upper pair overlaps by one minim; the lower pair by one bar. In the bass at 52 the large upward leap is replaced by a downward step. The full five-part texture returns at 53.'},
 {start:55,end:67,label:'Simultaneous entries and preparation',entries:'Soprano II and alto 55 · episode 57–67 · dominant pedal 62–63',detail:'The two entries begin together on B♭ and E♭. Their continuation gives way to a four-part episode built from crotchet figures. The bass holds F through bar 62 and the first half of 63; subsequent descending bass notes lead to the last stretto.'},
 {start:67,end:75,label:'Five-part stretto and coda',entries:'Soprano I 67:2 → soprano II 68 → alto 68:2 → tenor 69 → bass 69:2',detail:'Each voice follows one minim after the previous entry, alternating subject and tonal-answer forms. The two answers alter their descending endings; the bass later changes D♭ to D natural. Altered answer-head allusions in bass 73 and tenor 74 precede the final B♭ major chord.'},
];
export const tonalEvents=[
 {id:'db25',bar:25,q:96,key:'D♭ major',short:'D♭',roman:'III',type:'cadence',evidence:'The bass moves A♭–D♭ as the soprano resolves C–D♭. F in soprano II and A♭ in the tenor complete the chord.'},
 {id:'eb27',bar:27,q:104,key:'E♭ minor',short:'E♭m',roman:'iv',type:'entry',evidence:'The answer-form entry begins B♭–E♭ in soprano II; E♭ in the alto and G♭ in soprano I establish the minor subdominant context.'},
 {id:'bb29',bar:29,q:112,key:'B♭ minor',short:'B♭m',roman:'i',type:'entry',evidence:'The tenor begins the subject on B♭. Its later D natural changes the closing third; this marker identifies the opening context rather than a cadence.'},
 {id:'ab37',bar:37,q:144,key:'A♭ major',short:'A♭',roman:'VII',type:'cadence',evidence:'The bass moves E♭–A♭ and soprano I resolves G–A♭. C in the alto and E♭ in the tenor supply the third and fifth.'},
 {id:'eb55',bar:55,q:216,key:'E♭ minor',short:'E♭m',roman:'iv',type:'cadence',evidence:'The bass B♭ resolves to E♭, with G♭ in the tenor and B♭ in soprano II. Two thematic entries begin on the cadential chord.'},
 {id:'f62',bar:62,q:244,key:'F major',short:'F',roman:'V',type:'arrival',evidence:'F in the bass and alto, with A in soprano II, establishes the dominant pedal. The tenor’s D♭ resolves to C on the next crotchet. V denotes dominant harmony, not a modulation.'},
 {id:'bb67',bar:67,q:266,key:'B♭ minor',short:'B♭m',roman:'i',type:'arrival',evidence:'The last stretto begins with B♭ above bass D♭ and soprano II’s F. The alto’s E♭ resolves to D♭ on the following crotchet, completing the tonic in first inversion.'},
 {id:'bb75',bar:75,q:296,key:'B♭ major',short:'B♭',roman:'I',type:'close',evidence:'The bass moves F–B♭ and soprano I resolves A–B♭. D natural in soprano II supplies the major third; the tenor retains F.'},
];
