export const voices=['Soprano','Alto','Bass'];
export const themes=[
 {id:'subject',title:'Subject / real answer',location:'Soprano, bars 1–3',text:'The real answer transposes the subject down a fifth without tonal alteration. The ascending quavers lead to a semiquaver turn, a leap to the minor sixth, then a trill on the fourth degree before the closing dominant. Later statements alter intervals, invert the line or conceal its head within a sequence.'},
 {id:'cs1',title:'Countersubject',location:'Soprano, bars 3–5',text:'The falling semiquaver head (c) is followed by the returning-note figure (d). The last five notes of c reverse the subject’s opening. Both components recur separately, in sequence and in inversion. At the bass entry in bar 6, the countersubject is divided between soprano and alto.'},
];
export const formalGroups=[
 {start:1,end:21,startQ:0,endQ:60.5,number:'I',label:'Exposition; direct and inverted stretti',range:'1–21',continuation:'S · A · B; additional entry; A-minor close'},
 {start:21,end:44,startQ:60.5,endQ:132,number:'II',label:'Inverted entries; corresponding close',range:'21–44',continuation:'Mixed stretti; tonic close and two-bar coda'},
];
export const sections=[
 {start:1,end:8,label:'Exposition',entries:'Subject: soprano, bar 1 · real answer: alto, bar 3 · subject: bass, bar 6; each on the second quaver',detail:'The first two entries overlap at the closing note. The countersubject begins with the falling semiquaver head (c); its returning-note figure (d), from bar 4 beat 2, later accompanies other portions of the subject. The bass entry receives the countersubject first in the soprano, then in the alto.'},
 {start:8,end:13,label:'Additional entry and first episode',entries:'Altered subject: soprano, bar 8 · concealed statement: bass, bars 11–13',detail:'The additional entry begins on E, changing its intervals rather than establishing E minor. The countersubject moves below it. The ensuing descending sequence embeds the bass subject-head in semiquaver figuration; its second bar and closing A remain recognisable. The alto adds an inverted subject-head fragment (hi) in bar 12.'},
 {start:13,end:17,label:'Direct and inverted combination',entries:'Soprano, bar 13 · inverted alto, bar 14; one bar apart',detail:'The direct statement raises the third of its opening ascent. The alto follows in inversion; the bass simultaneously recalls the direct head. The countersubject’s falling head continues above the chromatic progression in bars 15–16.'},
 {start:17,end:21,label:'Stretto and dominant close',entries:'Bass, bar 17 · alto, bar 18; at the octave after one bar',detail:'Both entries are direct, with local major-third alterations. The returning-note figure (d) accompanies the opening quavers here, rather than the latter part of the subject. The cadence at bar 21 closes in A minor. Bars 39–42 return to this pattern a fourth higher.'},
 {start:21,end:27,label:'Mixed stretto and inverted episode',entries:'Direct bass, bar 21 · inverted soprano, bar 22 · inverted bass, bar 23',detail:'Entries follow at one-bar distances, with altered intervals and endings. The alto is silent during bars 22–24. In bars 25–26 the soprano inverts the countersubject’s returning-note figure, against inverted head fragments in the lower parts.'},
 {start:27,end:34,label:'Three-part stretto and corresponding episode',entries:'Inverted answer: soprano, bar 27 · subject: alto, bar 28 · inverted answer: bass, bar 29',detail:'The inverted outer parts surround the direct alto statement. The episode in bars 30–33 inverts the earlier disposition: the semiquaver sequence and concealed statement lie in the soprano. G minor is reached during bar 31; the following sequence returns to D minor at bar 34.'},
 {start:34,end:39,label:'Varied entry and head sequences',entries:'Varied bass subject, bar 34 · paired direct and inverted heads, bar 35',detail:'The bass changes the head’s minor third to major and divides the crotchets of the second bar into quavers. The soprano and alto then combine direct and inverted heads. In bars 36–38 the lower parts sequence inverted heads in thirds beneath the countersubject’s falling semiquavers.'},
 {start:39,end:44,label:'Final stretto and coda',entries:'Bass, bar 39 · alto, bar 40; at the octave after one bar',detail:'The closing stretto transposes bars 17–20 into D minor. F♯ in the bass of bar 40 preserves the parallel with C♯ in bar 18. The cadence in bar 43 begins a two-bar tonic pedal: additional parts set direct and inverted heads in thirds, before the D-major final chord.'},
];
export const tonalEvents=[
 {id:'d6',bar:6,q:15,key:'D minor',short:'Dm',roman:'i',type:'cadence',evidence:'The closing G and E above the descending alto resolve to F and D; the bass entry follows on the second quaver.'},
 {id:'a21',bar:21,q:60,key:'A minor',short:'Am',roman:'v',type:'cadence',evidence:'E in the bass, B in the alto and G♯ in the soprano resolve to A in all parts. The tonic third is omitted.'},
 {id:'d25',bar:25,q:72,key:'D minor',short:'Dm',roman:'i',type:'cadence',evidence:'The bass C♯ resolves to D below F in the soprano, ending the inverted bass entry.'},
 {id:'d28',bar:28,q:81,key:'D minor',short:'Dm',roman:'i',type:'arrival',evidence:'The preceding dominant seventh, represented by C♯, E and G, resolves to D and F before the alto entry.'},
 {id:'g31',bar:31,q:90.25,key:'G minor',short:'Gm',roman:'iv',type:'cadence',evidence:'The bass reaches G on the downbeat; the soprano’s C resolves to B♭ a semiquaver later, as the alto reaches G.'},
 {id:'d34',bar:34,q:99,key:'D minor',short:'Dm',roman:'i',type:'arrival',evidence:'C♯–E–B♭ resolves to the first-inversion D-minor chord F–A–D, before the bass subject begins.'},
 {id:'d43',bar:43,q:126,key:'D minor',short:'Dm',roman:'i',type:'cadence',evidence:'The A dominant resolves to D octaves, beginning the tonic pedal. The third is omitted at the cadence and raised in the coda.'},
 {id:'D44',bar:44,q:129,key:'D major',short:'D',roman:'I',type:'close',evidence:'The final six-part chord contains D, F♯ and A over the sustained tonic bass.'},
];
