export const voices=['Soprano I','Soprano II','Alto','Tenor','Bass'];
export const formalGroups=[
 {start:1,end:34,number:'I',label:'First subject',range:'1–34',continuation:'Exposition; further entries; cadence in E'},
 {start:35,end:93,number:'II',label:'Three subjects',range:'35–93',continuation:'S2 from 35; S3 from 49; triple counterpoint'},
 {start:94,end:115,number:'III',label:'Final stretti',range:'94–115',continuation:'S1 and S3; dominant and tonic pedals'},
];
export const themes=[
 {id:'subject',title:'First subject / real answer',location:'Bass, bars 1–4; real answer: tenor, bar 4',text:'Five notes, centred on the diminished fourth B♯–E. The real answer transposes the subject up a fifth. The fourth entry, in soprano II at 12:2, instead takes a tonal form leading to F♯ minor. Later entries shorten the opening note, prolong the ending or retain only the head.'},
 {id:'subject2',title:'Second subject',location:'Soprano I, from 35:1½',text:'Three ascending crotchets introduce a descending quaver sequence. Its variable length allows it to accompany successive entries of the first subject. The tenor inverts it at 41–43; its final appearance is in the tenor at 92–94.'},
 {id:'subject3',title:'Third subject',location:'Alto, from 49:1½',text:'An upbeat fourth, repeated crotchets and a quaver turn. With the first two subjects it forms triple counterpoint: the orders from top to bottom are 1–2–3 at 49, 3–2–1 at 52, 1–3–2 at 67 and 2–3–1 at 74. Its increasingly close stretti dominate the final section.'},
];
export const sections=[
 {start:1,end:18,label:'Exposition',entries:'S1: bass 1 · real answer: tenor 4 · alto 7:2 · soprano II 12:2 · soprano I 14:2',detail:'The voices enter from bass to soprano. A two-bar link separates alto and soprano II. The accompaniment to the tenor entry recurs beneath the alto, but does not become a fixed countersubject. Its descending crotchet figure (d), first heard in the bass at 7, supplies much of the subsequent texture, with inversion and diminution.'},
 {start:19,end:34,label:'Further entries of S1',entries:'Tenor 19:2 and 22:2½ · alto 25:2 · bass 29:2 · alto 32:2',detail:'The entries pass through G♯ minor, F♯ minor, C♯ minor, B major and E major. The E major cadence at 35 closes the opening section; the second subject enters immediately afterwards.'},
 {start:35,end:48,label:'S1 with S2',entries:'S1: tenor 35:2 · alto 38:2 · soprano II 44:2 · soprano I 48',detail:'The second subject continues above the first two entries. Its inversion in the tenor forms the episode at 41–43. At 44 it moves to the bass. The soprano’s quaver figure at 48 becomes the ornamented opening note of S1 in F♯ minor; treating only the last quaver as the entry would obscure this continuity.'},
 {start:49,end:61,label:'Triple counterpoint',entries:'S3: alto 49:1½ · S1: tenor 51:2 · soprano II 54:2 · soprano I 59',detail:'The third subject completes the combination. Successive changes of register establish the subjects’ contrapuntal invertibility. S1’s endings at 54–57 and 59–62 pass into S3 rather than retaining the model’s separate final note.'},
 {start:62,end:72,label:'S3 in stretto; remote entry',entries:'S3: alto 64:1½ → bass 65:1½ · S1: soprano I 66, D♯ minor',detail:'The third subject enters at one bar’s distance. The next first-subject entry moves to D♯ minor; its close is chromatically altered. The ensuing passage continues S2 and S3 while returning towards C♯ minor.'},
 {start:73,end:88,label:'Tonic entries and S3 stretto',entries:'S1: bass 73 · soprano I 76 · tenor 81 · S3: tenor 84:1½ → soprano II 85:1½ → bass 86:1½',detail:'Three successive tonic entries vary the disposition of all three subjects. The bass at 73 displaces S1’s second note by an octave. The following stretto leads to F♯ minor at 88.'},
 {start:89,end:101,label:'Transition and combined stretti',entries:'S1: soprano I 89 and 94 · soprano II 95:2 · soprano I 96:2 · bass 97:2 · tenor head 100',detail:'S2 disappears after the tenor’s 92–94 statement. From 94 the shortened first subject overlaps itself while S3 continues in stretto. At 98–99 the latter enters at half-bar intervals: soprano II 98:1½, tenor 98:2½, soprano I 99:1½.'},
 {start:102,end:115,label:'Pedals and close',entries:'Dominant pedal 105 · S1: soprano I 107 · tonic pedal 112 · S1: soprano II 112:2',detail:'S3 continues in stretto above the dominant pedal. S1 at 107 delays its third note across the bar-line. The tonic pedal begins beneath a dissonant sixth and suspended fifth at 112. The final subdominant entry, with the broadened S3 in the alto, resolves to C♯ major.'},
];
export const tonalEvents=[
 {id:'fs12',bar:12,q:46,key:'F♯ minor',short:'F♯m',roman:'iv',type:'entry',evidence:'The fourth entry takes a tonal answer form, G♯–E♯–A–G♯–F♯, directed towards the subdominant. This marks its tonal context, not a cadence at the onset.'},
 {id:'gs22',bar:22,q:84,key:'G♯ minor',short:'G♯m',roman:'v',type:'cadence',evidence:'The bass reaches G♯ beneath B in soprano I and G♯ in the two continuing inner parts, completing the tenor’s dominant-key entry.'},
 {id:'b29',bar:29,q:114,key:'B major',short:'B',roman:'VII',type:'entry',evidence:'The bass introduces S1 as B–A♯–D♯–C♯–B. The marker identifies the key of the entry; its opening is not a B major cadence.'},
 {id:'e35',bar:35,q:136,key:'E major',short:'E',roman:'III',type:'cadence',evidence:'The bass moves B–E under E in soprano I and alto, G♯ in soprano II and B in the tenor. This cadence closes the first formal section.'},
 {id:'cs38',bar:38,q:148,key:'C♯ minor',short:'C♯m',roman:'i',type:'cadence',evidence:'The bass moves from B♯ to C♯ as the soprano reaches E and the tenor completes S1 on C♯.'},
 {id:'fs51',bar:51,q:201,key:'F♯ minor',short:'F♯m',roman:'iv',type:'arrival',evidence:'The soprano’s prolonged G♯ resolves to F♯ above A in soprano II; the alto moves to F♯ below. This completes the ornamented subject entry begun at 48.'},
 {id:'ds66',bar:66,q:260,key:'D♯ minor',short:'D♯m',roman:'ii',type:'entry',evidence:'S1 enters as D♯–C𝄪–F♯–E♯, with a chromatically altered close. This is the key of the subject entry, not a claim of a D♯ minor tonic chord at its onset.'},
 {id:'cs73',bar:73,q:288,key:'C♯ minor',short:'C♯m',roman:'i',type:'arrival',evidence:'The bass re-enters on low C♯ with S1 after the preceding F♯ minor harmony. The upper F♯ resolves to E on beat 2, completing the tonic arrival with a 4–3 suspension.'},
 {id:'fs88',bar:88,q:348,key:'F♯ minor',short:'F♯m',roman:'iv',type:'cadence',evidence:'The bass moves E♯–F♯ below A and C♯. Soprano II’s G♯ suspension resolves to F♯ on beat 2.'},
 {id:'gs105',bar:105,q:416,key:'G♯ major',short:'G♯',roman:'V',type:'arrival',evidence:'The dominant pedal begins on G♯ beneath B♯, D♯ and F♯: a dominant seventh of C♯. V here denotes the dominant harmony, not a modulation to G♯ major.'},
 {id:'cs115',bar:115,q:456,key:'C♯ major',short:'C♯',roman:'I',type:'cadence',evidence:'Over the tonic pedal, the alto resolves D♯ to E♯ while the other parts retain C♯ and G♯, completing the major close.'},
];
