// Generated by scripts/sync_catalogue.mjs from content/catalogue.json.
import type {FugueData,WorkMetadata} from './types';
import metadata0 from '../../content/fugues/wtc-ii-22/metadata.json';
export const catalogue:WorkMetadata[]=[metadata0];
const loaders:Record<string,()=>Promise<FugueData>>={
 "wtc-ii-22":()=>import('../../content/fugues/wtc-ii-22/study').then(module=>module.default),
};
export async function loadStudy(id:string):Promise<FugueData|undefined>{
 return Object.hasOwn(loaders,id)?loaders[id]():undefined;
}
