// Generated by scripts/build_collection.mjs from content/catalogue.json.
import type {FugueData,WorkMetadata} from './types';
import metadata0 from '../../content/fugues/wtc-i-01/metadata.json';
import metadata1 from '../../content/fugues/wtc-i-02/metadata.json';
import metadata2 from '../../content/fugues/wtc-i-03/metadata.json';
import metadata3 from '../../content/fugues/wtc-i-04/metadata.json';
import metadata4 from '../../content/fugues/wtc-i-05/metadata.json';
import metadata5 from '../../content/fugues/wtc-i-06/metadata.json';
import metadata6 from '../../content/fugues/wtc-i-07/metadata.json';
import metadata7 from '../../content/fugues/wtc-i-08/metadata.json';
import metadata8 from '../../content/fugues/wtc-i-09/metadata.json';
import metadata9 from '../../content/fugues/wtc-i-15/metadata.json';
import metadata10 from '../../content/fugues/wtc-i-22/metadata.json';
import metadata11 from '../../content/fugues/wtc-i-23/metadata.json';
import metadata12 from '../../content/fugues/wtc-ii-04/metadata.json';
import metadata13 from '../../content/fugues/wtc-ii-09/metadata.json';
import metadata14 from '../../content/fugues/wtc-ii-22/metadata.json';
export const catalogue:WorkMetadata[]=[metadata0,metadata1,metadata2,metadata3,metadata4,metadata5,metadata6,metadata7,metadata8,metadata9,metadata10,metadata11,metadata12,metadata13,metadata14];
const loaders:Record<string,()=>Promise<FugueData>>={
 "wtc-i-01":()=>import('../../content/fugues/wtc-i-01/study').then(module=>module.default),
 "wtc-i-02":()=>import('../../content/fugues/wtc-i-02/study').then(module=>module.default),
 "wtc-i-03":()=>import('../../content/fugues/wtc-i-03/study').then(module=>module.default),
 "wtc-i-04":()=>import('../../content/fugues/wtc-i-04/study').then(module=>module.default),
 "wtc-i-05":()=>import('../../content/fugues/wtc-i-05/study').then(module=>module.default),
 "wtc-i-06":()=>import('../../content/fugues/wtc-i-06/study').then(module=>module.default),
 "wtc-i-07":()=>import('../../content/fugues/wtc-i-07/study').then(module=>module.default),
 "wtc-i-08":()=>import('../../content/fugues/wtc-i-08/study').then(module=>module.default),
 "wtc-i-09":()=>import('../../content/fugues/wtc-i-09/study').then(module=>module.default),
 "wtc-i-15":()=>import('../../content/fugues/wtc-i-15/study').then(module=>module.default),
 "wtc-i-22":()=>import('../../content/fugues/wtc-i-22/study').then(module=>module.default),
 "wtc-i-23":()=>import('../../content/fugues/wtc-i-23/study').then(module=>module.default),
 "wtc-ii-04":()=>import('../../content/fugues/wtc-ii-04/study').then(module=>module.default),
 "wtc-ii-09":()=>import('../../content/fugues/wtc-ii-09/study').then(module=>module.default),
 "wtc-ii-22":()=>import('../../content/fugues/wtc-ii-22/study').then(module=>module.default),
};
export async function loadStudy(id:string):Promise<FugueData|undefined>{
 return Object.hasOwn(loaders,id)?loaders[id]():undefined;
}
