// Generated by scripts/build_collection.mjs from content/catalogue.json.
import type {FugueData,WorkMetadata} from './types';
import metadata0 from '../../content/fugues/wtc-i-02/metadata.json';
import metadata1 from '../../content/fugues/wtc-ii-04/metadata.json';
import metadata2 from '../../content/fugues/wtc-ii-09/metadata.json';
import metadata3 from '../../content/fugues/wtc-ii-22/metadata.json';
export const catalogue:WorkMetadata[]=[metadata0,metadata1,metadata2,metadata3];
const loaders:Record<string,()=>Promise<FugueData>>={
 "wtc-i-02":()=>import('../../content/fugues/wtc-i-02/study').then(module=>module.default),
 "wtc-ii-04":()=>import('../../content/fugues/wtc-ii-04/study').then(module=>module.default),
 "wtc-ii-09":()=>import('../../content/fugues/wtc-ii-09/study').then(module=>module.default),
 "wtc-ii-22":()=>import('../../content/fugues/wtc-ii-22/study').then(module=>module.default),
};
export async function loadStudy(id:string):Promise<FugueData|undefined>{
 return Object.hasOwn(loaders,id)?loaders[id]():undefined;
}
