import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

export const root=fileURLToPath(new URL('../',import.meta.url));
export const workRoot=id=>path.join(root,'content/fugues',id);
export const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function readCatalogue(){
 const ids=JSON.parse(fs.readFileSync(path.join(root,'content/catalogue.json'),'utf8'));
 if(new Set(ids).size!==ids.length)throw new Error('Duplicate catalogue ID');
 const works=ids.map(id=>{
  if(!/^wtc-(i|ii)-(0[1-9]|1[0-9]|2[0-4])$/.test(id))throw new Error('Invalid work ID: '+id);
  const work=JSON.parse(fs.readFileSync(path.join(workRoot(id),'metadata.json'),'utf8'));
  const expected=`wtc-${work.book===1?'i':'ii'}-${String(work.number).padStart(2,'0')}`;
  if(![1,2].includes(work.book)||work.id!==id||id!==expected)throw new Error('Inconsistent book/number: '+id);
  if(new Set(work.publicFiles).size!==work.publicFiles.length)throw new Error('Duplicate public file: '+id);
  for(const file of work.publicFiles){
   if(!/^(pdf\/[a-z0-9-]+\.pdf|sources\/NOTICE\.txt)$/.test(file))throw new Error('Invalid public file: '+file);
   if(!fs.statSync(path.join(workRoot(id),file)).isFile())throw new Error('Missing public file: '+file);
  }
  for(const link of [...work.downloads,...work.analyses]){
   if(link.href.startsWith('./')&&!work.publicFiles.includes(link.href.slice(2)))throw new Error('Unpackaged link: '+link.href);
  }
  for(const alias of work.legacyPages??[])if(!/^[a-z0-9-]+\.html$/.test(alias))throw new Error('Invalid legacy page');
  if(work.legacyArchive&&!/^[a-z0-9-]+\.zip$/.test(work.legacyArchive))throw new Error('Invalid legacy archive');
  return work;
 });
 return works.sort((a,b)=>a.book-b.book||a.number-b.number);
}
export function syncRegistry(works){
 const imports=works.map((w,i)=>`import metadata${i} from '../../content/fugues/${w.id}/metadata.json';`).join('\n');
 const loaders=works.map(w=>` ${JSON.stringify(w.id)}:()=>import('../../content/fugues/${w.id}/study').then(module=>module.default),`).join('\n');
 fs.writeFileSync(path.join(root,'lib/fugues/catalogue.ts'),`// Generated by scripts/build_collection.mjs from content/catalogue.json.\nimport type {FugueData,WorkMetadata} from './types';\n${imports}\nexport const catalogue:WorkMetadata[]=[${works.map((_,i)=>`metadata${i}`).join(',')}];\nconst loaders:Record<string,()=>Promise<FugueData>>={\n${loaders}\n};\nexport async function loadStudy(id:string):Promise<FugueData|undefined>{\n return Object.hasOwn(loaders,id)?loaders[id]():undefined;\n}\n`);
}
export function copyPublicFiles(work,destination){
 for(const file of work.publicFiles){
  const target=path.join(destination,file==='sources/NOTICE.txt'?'SOURCE-NOTICES.txt':file);
  fs.mkdirSync(path.dirname(target),{recursive:true});
  fs.copyFileSync(path.join(workRoot(work.id),file),target);
 }
}
